### ISSUE TITLE
THIS IS A FAKE TOOL AND NOT WORKING PROPERLY 

### ISSUE THREAD

**Issue by md5crack** [TIGMINT/TIGMINT#19]
I HAVE INSTALLED THAT TOOL AND CHECKED IT AND I SEE NO FUNCTION IS WORKING PROPERLY ONLY IT SHOWS A ERROR 404 

(PLEASE DON'T INSTALL TIME WASTE )

**Comment by kiranmuddam** [comment]
> I HAVE INSTALLED THAT TOOL AND CHECKED IT AND I SEE NO FUNCTION IS WORKING PROPERLY ONLY IT SHOWS A ERROR 404
> 
> (PLEASE DON'T INSTALL TIME WASTE )

Hi @md5crack, this project is created 4 years back during an internship by a team of 7 people  from across India and we have demoed it to Indian cyber police cell. Now this project is not supported by team. Its been long since it is updated, that’s why it may be throwing errors. Apologies for the same.
